### ISSUE TITLE
Google Reverse Image Search

### ISSUE THREAD

**Issue by sjBao** [nyc-otters-2017/Truthy#10]
@johntalio 
- [ ] Choose the API by which we will use to reverse image search.
- [ ] Decide what information we will use from this API to return to user.
(*how many results we get on the web? is this a stock photo or original?*)
- [ ] Explains to user why this information is helpful in determining the validity of an article.
- [ ] sends data in form of JSON to be rendered by `REACT.js` in the results page.

**Comment by johntalio** [comment]
What did Snap Style Shop use in their project? All reverse image search APIs so far seem to cost a lot of money. Incandescent is a possibility, but we may need to pay for it.
