### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by sjBao** [nyc-otters-2017/Truthy#11]
- [x] Get instructor feedback about this feature.
- [x] How will we grab quotable statements from an article?
- [x] Play with Storyzy.
- [x] Grabs all quotable content from an article piece and return as collection to user.
- [x] Explains to user why this is important.
@Jefferson-Faseler @johntalio @polymer940c 
- [x] **Does this feature sound lame? Because basically we are just telling users to google it lol.**

**Comment by johntalio** [comment]
From Storyzy_NewsData API description at Mashape: "Storyzy_NewsData API (by Trooclick) creates structured data from the text of news articles using NLP technology. The data delivered includes automatically extracted quotes (uniquely capable of extracting BOTH direct and indirect quoted speech with anaphora resolution), speakers, speaker pictures (when available), story headlines, story summaries, companies involved, company logos (when available), all related article URLs, duplicate article detection, and more. This JSON API is RESTful, and more information is available by contacting Storyzy at api@trooclick.com"

This could be excellent. There is a free option, but you need to provide credit card information.

**Comment by johntalio** [comment]
If we choose to use this API, I think it would basically cover quotes for the app.

**Comment by johntalio** [comment]
Storyzy_NewsData test on Mashape not responding - tried contacting Storyzy, no response yet. May need to look into alternatives.
