### ISSUE TITLE
Black Lists Checker

### ISSUE THREAD

**Issue by sjBao** [nyc-otters-2017/Truthy#8]
@polymer940c 
- [x] make seed data of blacklisted sites.
- [x] checks to see if URL is associated with blacklisted sites
- [x] if associated returns message to notify user.
---
- [x] makes API call to full-contact-company (how feasible is this?)
- [x] returns company info
- [x] renders both data in the results page

**Comment by justanotherkevin** [comment]
full-contact response received. need navigation to bios(there are 6 for cnn... number varies by site?)
